import type { Metadata } from 'next';
import './globals.css';
import Navbar from '@/components/global/Navbar';
import * as fonts from './fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${fonts.josefin_sans.variable} ${fonts.roboto_mono.variable} font-sans `}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
